[package]
name = "butterscotch-ecs"
version = "0.1.0"
authors = ["Michael Baker <butterscotch@notvery.moe>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]

butterscotch-common = { path = "../common" }