[package]
name = "butterscotch-events"
version = "0.1.0"
authors = ["Michael Baker <butterscotch@notvery.moe>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
static_assertions = "1.1.0"
butterscotch-common = { path = "../common" }