[package]
name = "butterscotch-common"
version = "0.1.0"
authors = ["Michael Baker <github@notvery.moe>"]
edition = "2018"

[features]
default = []
web     = [
    "instant/wasm-bindgen"
]

[dependencies]
instant = "0.1"
static_assertions = "1.1"
raw-window-handle = "0.3"