[package]
name = "const_gen"
version = "0.1.0"
authors = ["Michael Baker <github@notvery.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
f128 = "0.2.6"
num-traits = "0.2.12"
num-format = "0.4.0"